import { AtSign, Camera, Check, Gift, Instagram, MapPin, Pencil, Plus, Trash2, Users, X } from 'lucide-react'
import { useRef, useState, type FormEvent } from 'react'
import { compressImage } from '../lib/storage'
import type { Exchange, ExchangeDraft, SocialPlatform } from '../types'

const blank: ExchangeDraft = { contact: '', platform: 'instagram', nickname: '', receiver: '', sender: '', note: '' }
function socialUrl(value: string) { const candidate = value.trim().startsWith('www.') ? `https://${value.trim()}` : value.trim(); try { const url = new URL(candidate); return ['http:', 'https:'].includes(url.protocol) ? url.href : undefined } catch { return undefined } }
function PlatformIcon({ platform, size = 17 }: { platform: SocialPlatform; size?: number }) { return platform === 'instagram' ? <Instagram size={size} aria-hidden="true" /> : <AtSign size={size} aria-hidden="true" /> }
function toDraft(exchange: Exchange): ExchangeDraft { return { contact: exchange.contactHandle, platform: exchange.contactPlatform ?? 'instagram', nickname: exchange.nickname ?? '', receiver: exchange.receiverItemText, sender: exchange.senderItemText, note: exchange.note ?? '', image: exchange.receiverItemImage } }

interface Props { exchanges: Exchange[]; onAdd: (draft: ExchangeDraft) => void; onUpdate: (id: string, draft: ExchangeDraft) => void; onToggle: (id: string, field: 'isPrepared' | 'isCompleted') => void; onDelete: (id: string) => void }

export function ExchangeList({ exchanges, onAdd, onUpdate, onToggle, onDelete }: Props) {
  const [isAdding, setIsAdding] = useState(false)
  const [editingId, setEditingId] = useState<string>()
  const [selected, setSelected] = useState<Exchange>()
  const [draft, setDraft] = useState<ExchangeDraft>(blank)
  const [loadingImage, setLoadingImage] = useState(false)
  const fileRef = useRef<HTMLInputElement>(null)
  const set = <K extends keyof ExchangeDraft>(field: K, value: ExchangeDraft[K]) => setDraft((current) => ({ ...current, [field]: value }))
  const closeEditor = () => { setIsAdding(false); setEditingId(undefined); setDraft(blank) }
  const openEditor = (exchange?: Exchange) => { setSelected(undefined); setEditingId(exchange?.id); setDraft(exchange ? toDraft(exchange) : blank); setIsAdding(true) }
  const selectImage = async (file?: File) => { if (!file) return; setLoadingImage(true); try { set('image', await compressImage(file)) } finally { setLoadingImage(false) } }
  const save = (event: FormEvent) => { event.preventDefault(); if (!draft.contact.trim() || !draft.sender.trim()) return; if (editingId) onUpdate(editingId, draft); else onAdd(draft); closeEditor() }

  return <section className="space-y-4"><div className="flex items-end justify-between"><div><p className="section-kicker">EXCHANGE LIST</p><h2 className="section-title">當日交換清單</h2></div><p className="text-sm font-bold text-slate-400">{exchanges.length} 位</p></div>
    {exchanges.length === 0 && <div className="rounded-3xl border border-dashed border-serenity-200 bg-serenity-50/60 px-6 py-10 text-center"><Gift className="mx-auto mb-3 text-serenity-400" size={32} /><p className="font-bold text-slate-700">還沒有交換夥伴</p><p className="mt-1 text-sm leading-relaxed text-slate-500">先把聯絡帳號和交換品項記下來，現場就不會手忙腳亂。</p></div>}
    <div className="grid grid-cols-2 gap-3">{exchanges.map((exchange) => { const url = socialUrl(exchange.contactHandle); const platform = exchange.contactPlatform ?? 'instagram'; return <article key={exchange.id} onClick={() => setSelected(exchange)} className={`min-w-0 cursor-pointer rounded-3xl border bg-white p-3 shadow-sm transition active:scale-[0.98] ${exchange.isCompleted ? 'border-emerald-200 opacity-75' : 'border-slate-100'}`}>
      {exchange.receiverItemImage ? <img src={exchange.receiverItemImage} alt="對方禮物" className="mb-3 h-28 w-full rounded-2xl object-cover" /> : <div className="mb-3 flex h-28 items-center justify-center rounded-2xl bg-serenity-50 text-serenity-500"><Gift size={28} /></div>}
      <div className="flex items-start justify-between gap-1"><div className="min-w-0">{url ? <a href={url} onClick={(event) => event.stopPropagation()} target="_blank" rel="noreferrer" className="flex min-h-7 items-center gap-1 truncate font-bold text-serenity-700 underline underline-offset-2"><PlatformIcon platform={platform} /><span className="truncate">{exchange.contactHandle}</span></a> : <p className="flex min-h-7 items-center gap-1 truncate font-bold text-slate-700"><PlatformIcon platform={platform} /><span className="truncate">{exchange.contactHandle}</span></p>}{exchange.nickname && <p className="truncate text-xs text-slate-400">{exchange.nickname}</p>}</div><div className="-mr-2 -mt-2 flex shrink-0"><button type="button" onClick={(event) => { event.stopPropagation(); openEditor(exchange) }} className="inline-flex h-9 w-9 items-center justify-center rounded-xl text-serenity-600 hover:bg-serenity-50" aria-label="編輯交換"><Pencil size={16} /></button><button type="button" onClick={(event) => { event.stopPropagation(); onDelete(exchange.id) }} className="inline-flex h-9 w-9 items-center justify-center rounded-xl text-slate-300 hover:bg-slate-100" aria-label="刪除交換"><Trash2 size={16} /></button></div></div>
      <p className="mt-3 text-xs leading-relaxed text-slate-500"><span className="font-bold text-slate-600">對方：</span>{exchange.receiverItemText || '尚未填寫'}</p><p className="mt-2 text-xs font-semibold leading-relaxed text-rosequartz-700"><span>我方：</span>{exchange.senderItemText}</p><div className="mt-3 space-y-2"><button type="button" onClick={(event) => { event.stopPropagation(); onToggle(exchange.id, 'isPrepared') }} className={`status-button w-full ${exchange.isPrepared ? 'status-ready' : ''}`}><Check size={15} />{exchange.isPrepared ? '已準備' : '未準備'}</button><button type="button" onClick={(event) => { event.stopPropagation(); onToggle(exchange.id, 'isCompleted') }} className={`status-button w-full ${exchange.isCompleted ? 'status-done' : ''}`}><Check size={15} />{exchange.isCompleted ? '已交換' : '未交換'}</button></div>
    </article> })}</div>
    {isAdding ? <form onSubmit={save} className="card space-y-3"><div className="flex items-center justify-between"><h3 className="font-bold text-slate-800">{editingId ? '編輯交換夥伴' : '新增交換夥伴'}</h3><button type="button" onClick={closeEditor} className="text-sm text-slate-400">取消</button></div><div className="grid grid-cols-2 gap-2">{(['instagram', 'threads'] as SocialPlatform[]).map((platform) => <button key={platform} type="button" onClick={() => set('platform', platform)} className={`min-h-11 rounded-xl text-sm font-bold ${draft.platform === platform ? 'bg-serenity-600 text-white' : 'bg-serenity-50 text-serenity-700'}`}><span className="inline-flex items-center gap-2"><PlatformIcon platform={platform} />{platform === 'instagram' ? 'Instagram' : 'Threads'}</span></button>)}</div><input required value={draft.contact} onChange={(event) => set('contact', event.target.value)} placeholder="帳號或完整社群網址" className="field" /><input value={draft.nickname} onChange={(event) => set('nickname', event.target.value)} placeholder="夥伴暱稱（可選）" className="field" /><textarea value={draft.receiver} onChange={(event) => set('receiver', event.target.value)} placeholder="對方的禮物描述（可選）" className="field min-h-20" /><textarea required value={draft.sender} onChange={(event) => set('sender', event.target.value)} placeholder="我要帶去交換的品項" className="field min-h-20" /><input value={draft.note} onChange={(event) => set('note', event.target.value)} placeholder="碰面地點或其他備註（可選）" className="field" /><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={(event) => selectImage(event.target.files?.[0])} /><button type="button" onClick={() => fileRef.current?.click()} className="secondary-button w-full"><Camera size={18} />{loadingImage ? '正在壓縮圖片…' : draft.image ? '已選擇照片，點擊可更換' : '加入對方禮物照片（可選）'}</button>{draft.image && <img src={draft.image} alt="對方禮物預覽" className="h-36 w-full rounded-2xl object-cover" />}<button className="primary-button w-full">{editingId ? '儲存交換變更' : '加入清單'}</button></form> : <button type="button" onClick={() => openEditor()} className="secondary-button w-full"><Users size={18} />新增交換夥伴</button>}
    {selected && <div className="fixed inset-0 z-50 flex items-end bg-slate-900/50 p-3 sm:items-center sm:justify-center" onClick={() => setSelected(undefined)}><article className="max-h-[92vh] w-full max-w-md overflow-y-auto rounded-3xl bg-white p-4 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="mb-3 flex items-center justify-between"><p className="text-sm font-bold text-slate-700">交換夥伴詳情</p><button type="button" onClick={() => setSelected(undefined)} className="icon-button text-slate-500" aria-label="關閉"><X /></button></div>{selected.receiverItemImage ? <img src={selected.receiverItemImage} alt="對方應援物大圖" className="h-[48vh] min-h-72 w-full rounded-2xl object-cover" /> : <div className="flex h-72 items-center justify-center rounded-2xl bg-serenity-50 text-serenity-500"><Gift size={52} /></div>}<div className="mt-4"><p className="font-bold text-slate-800">{selected.nickname || selected.contactHandle}</p><p className="mt-2 text-sm text-slate-600">對方應援物：{selected.receiverItemText || '尚未填寫'}</p><p className="mt-2 text-sm font-semibold text-rosequartz-700">我方交換品項：{selected.senderItemText}</p>{selected.note && <p className="mt-2 flex gap-1 text-sm text-slate-500"><MapPin size={16} />{selected.note}</p>}</div><button type="button" onClick={() => openEditor(selected)} className="primary-button mt-5 w-full"><Pencil size={18} />編輯此交換資料</button></article></div>}
  </section>
}
