import { Heart, Plus } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { EventCard } from './components/EventCard'
import { EventDetail } from './components/EventDetail'
import { EventForm } from './components/EventForm'
import { createId, readData } from './lib/storage'
import { isSupabaseConfigured } from './lib/supabase'
import { getSignedInUser, initializeData, persistData, signInWithEmail, signUpWithEmail } from './services/dataService'
import type { AppData, ExchangeDraft, ExpenseAmount } from './types'

export default function App() {
  const [data, setData] = useState<AppData>(readData)
  const [selectedEventId, setSelectedEventId] = useState<string | null>(null)
  const [showForm, setShowForm] = useState(false)
  const [editingEventId, setEditingEventId] = useState<string>()
  const [notice, setNotice] = useState('')
  const [isReady, setIsReady] = useState(false)
  const [needsLogin, setNeedsLogin] = useState(false)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [authMode, setAuthMode] = useState<'signIn' | 'signUp'>('signIn')
  const [isAuthenticating, setIsAuthenticating] = useState(false)
  useEffect(() => {
    let active = true
    const load = async () => {
      try {
        if (isSupabaseConfigured && !(await getSignedInUser())) { if (active) setNeedsLogin(true); return }
        const initialData = await initializeData()
        if (active) setData(initialData)
      } catch (error) { if (active) setNotice(`雲端連線失敗：${(error as Error).message}`) } finally { if (active) setIsReady(true) }
    }
    load()
    return () => { active = false }
  }, [])
  useEffect(() => {
    if (!isReady || needsLogin) return
    const timer = window.setTimeout(() => { persistData(data).catch((error: Error) => setNotice(`資料同步失敗：${error.message}`)) }, 500)
    return () => window.clearTimeout(timer)
  }, [data, isReady])
  const selected = data.events.find((event) => event.id === selectedEventId)
  const editingEvent = data.events.find((event) => event.id === editingEventId)
  const notify = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(''), 2200) }
  const eventExpenses = useMemo(() => data.expenses.filter((item) => item.eventId === selectedEventId), [data.expenses, selectedEventId])
  const eventDates = useMemo(() => data.dates.filter((item) => item.eventId === selectedEventId).sort((a, b) => a.dateLabel.localeCompare(b.dateLabel)), [data.dates, selectedEventId])
  const expenseTotal = (expense: { amount: number; amounts?: ExpenseAmount[] }) => expense.amounts?.reduce((sum, row) => sum + row.amount, 0) ?? expense.amount
  const addEvent = (title: string, firstDate: string, posterImage?: string) => { const id = createId(); setData((current) => ({ ...current, events: [{ id, title, createdAt: new Date().toISOString(), posterImage }, ...current.events], dates: firstDate ? [...current.dates, { id: createId(), eventId: id, dateLabel: firstDate }] : current.dates })); setShowForm(false); setSelectedEventId(id); notify('活動已建立') }
  const updateEvent = (title: string, firstDate: string, posterImage?: string) => { if (!editingEvent) return; setData((current) => { const existingDates = current.dates.filter((date) => date.eventId === editingEvent.id); const dates = firstDate ? existingDates.length ? current.dates.map((date) => date.id === existingDates[0].id ? { ...date, dateLabel: firstDate } : date) : [...current.dates, { id: createId(), eventId: editingEvent.id, dateLabel: firstDate }] : current.dates; return { ...current, events: current.events.map((event) => event.id === editingEvent.id ? { ...event, title, posterImage } : event), dates } }); setEditingEventId(undefined); notify('活動已更新') }
  const addExchange = (eventDateId: string, draft: ExchangeDraft) => { setData((current) => ({ ...current, exchanges: [...current.exchanges, { id: createId(), eventDateId, contactHandle: draft.contact, contactPlatform: draft.platform, nickname: draft.nickname, receiverItemText: draft.receiver, receiverItemImage: draft.image, senderItemText: draft.sender, note: draft.note, isPrepared: false, isCompleted: false }] })); notify('交換夥伴已加入') }
  const updateExchange = (id: string, draft: ExchangeDraft) => { setData((current) => ({ ...current, exchanges: current.exchanges.map((exchange) => exchange.id === id ? { ...exchange, contactHandle: draft.contact, contactPlatform: draft.platform, nickname: draft.nickname, receiverItemText: draft.receiver, receiverItemImage: draft.image, senderItemText: draft.sender, note: draft.note } : exchange) })); notify('交換資料已更新') }

  if (!isReady) return <main className="flex min-h-screen items-center justify-center bg-serenity-50 text-sm font-bold text-serenity-700">正在讀取你的應援資料…</main>
  if (needsLogin) return <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-rosequartz-50 via-serenity-50 to-slate-50 p-4"><form onSubmit={async (event) => { event.preventDefault(); if (!email.trim() || !password) return; if (authMode === 'signUp' && password !== confirmPassword) { setNotice('兩次輸入的密碼不一致。'); return } if (authMode === 'signUp' && password.length < 8) { setNotice('密碼請至少設定 8 碼。'); return } setIsAuthenticating(true); try { if (authMode === 'signUp') { const session = await signUpWithEmail(email.trim(), password, window.location.origin); if (!session) { setNotice('驗證信已寄出，請完成信箱驗證後再登入。'); return } } else { await signInWithEmail(email.trim(), password) } const initialData = await initializeData(); setData(initialData); setNeedsLogin(false); setNotice('登入成功，雲端同步已啟用。') } catch (error) { setNotice(`登入失敗：${(error as Error).message}`) } finally { setIsAuthenticating(false) } }} className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-sm"><p className="section-kicker">CLOUD SYNC</p><h1 className="mt-1 text-2xl font-black text-slate-800">{authMode === 'signIn' ? '登入你的應援資料' : '建立你的帳號'}</h1><p className="mt-2 text-sm leading-relaxed text-slate-500">使用同一個 Email 與密碼登入手機、電腦，即可同步同一份資料。</p><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={() => { setAuthMode('signIn'); setNotice('') }} className={`min-h-11 rounded-xl text-sm font-bold ${authMode === 'signIn' ? 'bg-serenity-600 text-white' : 'bg-serenity-50 text-serenity-700'}`}>登入</button><button type="button" onClick={() => { setAuthMode('signUp'); setNotice('') }} className={`min-h-11 rounded-xl text-sm font-bold ${authMode === 'signUp' ? 'bg-serenity-600 text-white' : 'bg-serenity-50 text-serenity-700'}`}>建立帳號</button></div><input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="你的 Email" className="field mt-3" /><input required type="password" minLength={8} autoComplete={authMode === 'signIn' ? 'current-password' : 'new-password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="密碼（至少 8 碼）" className="field mt-3" />{authMode === 'signUp' && <input required type="password" minLength={8} autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} placeholder="再次輸入密碼" className="field mt-3" />}{notice && <p className="mt-3 text-sm text-serenity-700">{notice}</p>}<button disabled={isAuthenticating} className="primary-button mt-4 w-full disabled:opacity-60">{isAuthenticating ? '處理中…' : authMode === 'signIn' ? '登入' : '建立帳號'}</button></form></main>
  if (selected) return <EventDetail event={selected} dates={eventDates} expenses={eventExpenses} exchanges={data.exchanges.filter((item) => eventDates.some((date) => date.id === item.eventDateId))} onBack={() => setSelectedEventId(null)} onAddDate={(dateLabel) => { const id = createId(); setData((current) => ({ ...current, dates: [...current.dates, { id, eventId: selected.id, dateLabel }] })); notify('已新增活動日期'); return id }} onDeleteDate={(id) => { setData((current) => ({ ...current, dates: current.dates.filter((date) => date.id !== id), exchanges: current.exchanges.filter((exchange) => exchange.eventDateId !== id) })); notify('日期與當日清單已刪除') }} onAddExpense={(itemName, amounts, note, itemImage) => { setData((current) => ({ ...current, expenses: [...current.expenses, { id: createId(), eventId: selected.id, itemName, amounts, amount: amounts.reduce((sum, row) => sum + row.amount, 0), note, itemImage }] })); notify('成本已加入') }} onUpdateExpense={(id, itemName, amounts, note, itemImage) => { setData((current) => ({ ...current, expenses: current.expenses.map((expense) => expense.id === id ? { ...expense, itemName, amounts, amount: amounts.reduce((sum, row) => sum + row.amount, 0), note, itemImage } : expense) })); notify('成本已更新') }} onDeleteExpense={(id) => setData((current) => ({ ...current, expenses: current.expenses.filter((item) => item.id !== id) }))} onAddExchange={addExchange} onUpdateExchange={updateExchange} onToggleExchange={(id, field) => { setData((current) => ({ ...current, exchanges: current.exchanges.map((item) => item.id === id ? { ...item, [field]: !item[field] } : item) })); notify('狀態已更新') }} onDeleteExchange={(id) => setData((current) => ({ ...current, exchanges: current.exchanges.filter((item) => item.id !== id) }))} />
  return <main className="min-h-screen bg-gradient-to-b from-rosequartz-50 via-serenity-50 to-slate-50"><div className="mx-auto max-w-2xl p-4 pb-12 sm:p-6"><header className="mb-7 pt-3 sm:pt-6"><div className="mb-3 flex items-center gap-2 text-rosequartz-600"><Heart size={20} fill="currentColor" /><span className="text-sm font-black tracking-widest">MY SUPPORT KIT</span></div><h1 className="text-3xl font-black tracking-tight text-slate-800">應援交換小幫手</h1><p className="mt-2 text-sm leading-relaxed text-slate-500">把成本、交換清單與現場進度，都放在同一個地方。</p></header>{notice && <div role="status" className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-slate-800 px-4 py-3 text-sm font-bold text-white shadow-lg">{notice}</div>}<div className="space-y-4">{data.events.map((event) => <EventCard key={event.id} event={event} total={data.expenses.filter((item) => item.eventId === event.id).reduce((sum, item) => sum + expenseTotal(item), 0)} dateCount={data.dates.filter((date) => date.eventId === event.id).length} onOpen={() => setSelectedEventId(event.id)} onEdit={() => { setEditingEventId(event.id); setShowForm(false) }} onDelete={() => { if (window.confirm(`確定刪除「${event.title}」及所有相關資料嗎？`)) { const dateIds = data.dates.filter((date) => date.eventId === event.id).map((date) => date.id); setData({ events: data.events.filter((item) => item.id !== event.id), expenses: data.expenses.filter((item) => item.eventId !== event.id), dates: data.dates.filter((item) => item.eventId !== event.id), exchanges: data.exchanges.filter((item) => !dateIds.includes(item.eventDateId)) }); notify('活動已刪除') } }} />)}</div>{editingEvent ? <div className="mt-5"><EventForm event={editingEvent} firstDate={data.dates.find((date) => date.eventId === editingEvent.id)?.dateLabel} onSubmit={updateEvent} onCancel={() => setEditingEventId(undefined)} /></div> : showForm ? <div className="mt-5"><EventForm onSubmit={addEvent} onCancel={() => setShowForm(false)} /></div> : <button type="button" onClick={() => setShowForm(true)} className="primary-button mt-5 w-full"><Plus size={20} />新增演唱會活動</button>}{data.events.length === 0 && !showForm && <div className="mt-10 text-center text-sm text-slate-400">從第一場活動開始，建立你的應援記錄。</div>}<p className="mt-8 text-center text-xs text-slate-400">目前以此裝置的瀏覽器暫存資料；雲端同步將在 Supabase 階段啟用。</p></div></main>
}
